const companies = [
  {
    name: "Linear Company",
    position: "Software Development level 1",
    location: "Brusia",
    type: "Full-time",
    salary: "60-90k",
    datePosted: "2023-10-28",
    description: `Welcome to Linear Company! We are a leading technology firm specializing in software development. Our team is dedicated to delivering innovative solutions that drive business success. Join us in Brusia and be part of our dynamic environment where your skills and ideas make a difference.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Tech Solutions",
    position: "Junior Developer",
    location: "Zandria",
    type: "Full-time",
    salary: "50-80k",
    datePosted: "2023-09-15",
    description: `Tech Solutions is committed to excellence in software development. As a Junior Developer, you will work in a collaborative environment to create impactful solutions for our clients in Zandria. Join our team and grow your career with us.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    name: "Innovatech",
    position: "Senior Developer",
    location: "Netherland",
    type: "Full-time",
    salary: "80-120k",
    datePosted: "2023-08-20",
    description: `At Innovatech, we push the boundaries of technology. Join our team of Senior Developers in Netherland and contribute to cutting-edge projects that shape the future. With competitive compensation and a stimulating work environment, Innovatech is where innovation meets excellence.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Future Systems",
    position: "Project Manager",
    location: "Arboria",
    type: "Full-time",
    salary: "70-110k",
    datePosted: "2023-07-05",
    description: `Future Systems is seeking a talented Project Manager to lead our initiatives in Arboria. As part of our team, you will oversee project lifecycles, ensuring timely delivery and client satisfaction. Join us and drive success with Future Systems.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    name: "Data Corp",
    position: "Data Analyst",
    location: "Quixonia",
    type: "Full-time",
    salary: "65-95k",
    datePosted: "2023-06-12",
    description: `Data Corp is dedicated to data-driven insights. Join our team of Data Analysts in Quixonia and analyze complex datasets to unlock valuable business insights. With Data Corp, your analytical skills drive impactful decisions.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    name: "Net Solutions",
    position: "System Administrator",
    location: "Atlantis",
    type: "Full-time",
    salary: "60-100k",
    datePosted: "2023-05-22",
    description: `Net Solutions is looking for a skilled System Administrator to maintain our network infrastructure in Atlantis. Join our team and ensure our systems operate efficiently to support our global operations.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    name: "Creative Minds",
    position: "UX/UI Designer",
    location: "Rivendell",
    type: "Full-time",
    salary: "55-85k",
    datePosted: "2023-04-30",
    description: `Creative Minds values creativity and user-centric design. As a UX/UI Designer in Rivendell, you will craft intuitive interfaces that enhance user experience across digital platforms. Join our team and unleash your creative potential.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    name: "Quality Assurance Inc.",
    position: "Quality Assurance",
    location: "Gondor",
    type: "Full-time",
    salary: "50-75k",
    datePosted: "2023-04-10",
    description: `Quality Assurance Inc. is committed to delivering superior quality. Join our team in Gondor and ensure our products meet the highest standards of excellence through rigorous testing and quality assurance processes.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    name: "Tech Support Co.",
    position: "Technical Support",
    location: "Elantris",
    type: "Full-time",
    salary: "45-70k",
    datePosted: "2023-03-18",
    description: `Tech Support Co. provides essential technical assistance. As part of our team in Elantris, you will resolve customer issues and ensure smooth operation of our products and services. Join us and make a difference with Tech Support Co.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    name: "Binary Solutions",
    position: "Software Development level 2",
    location: "Narnia",
    type: "Full-time",
    salary: "70-100k",
    datePosted: "2023-02-25",
    description: `Binary Solutions is dedicated to advanced software development. Join our team in Narnia and work on complex projects that push technological boundaries. With Binary Solutions, your expertise drives innovation and growth.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    name: "Prime Tech",
    position: "Junior Developer",
    location: "Brusia",
    type: "Full-time",
    salary: "50-80k",
    datePosted: "2023-01-30",
    description: `Prime Tech fosters talent in software development. Join our team in Brusia as a Junior Developer and gain hands-on experience in building impactful solutions. With Prime Tech, your career journey begins with innovation and growth.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    name: "Digital Pioneers",
    position: "Senior Developer",
    location: "Zandria",
    type: "Full-time",
    salary: "80-120k",
    datePosted: "2022-12-15",
    description: `Digital Pioneers leads the way in software development. As a Senior Developer in Zandria, you will spearhead projects that transform industries. Join Digital Pioneers and drive innovation with cutting-edge technologies.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    name: "NextGen Systems",
    position: "Project Manager",
    location: "Netherland",
    type: "Full-time",
    salary: "70-110k",
    datePosted: "2022-11-22",
    description: `NextGen Systems delivers visionary projects. Join our team in Netherland as a Project Manager and oversee initiatives that redefine success. With NextGen Systems, your leadership shapes the future of technology.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    name: "Insight Analytics",
    position: "Data Analyst",
    location: "Arboria",
    type: "Full-time",
    salary: "65-95k",
    datePosted: "2022-10-10",
    description: `Insight Analytics transforms data into actionable insights. Join our team in Arboria as a Data Analyst and uncover strategic opportunities through data-driven analysis. With Insight Analytics, your insights drive informed decisions.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    name: "Network Solutions",
    position: "System Administrator",
    location: "Quixonia",
    type: "Full-time",
    salary: "60-100k",
    datePosted: "2022-09-18",
    description: `Network Solutions ensures seamless operations. Join our team in Quixonia as a System Administrator and maintain robust network infrastructure. With Network Solutions, your expertise keeps us connected and secure.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    name: "Design Masters",
    position: "UX/UI Designer",
    location: "Atlantis",
    type: "Full-time",
    salary: "55-85k",
    datePosted: "2022-08-05",
    description: `Design Masters crafts exceptional user experiences. Join our team in Atlantis as a UX/UI Designer and shape intuitive interfaces that captivate users. With Design Masters, your creativity sets new standards in digital design.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    name: "QA Experts",
    position: "Quality Assurance",
    location: "Rivendell",
    type: "Full-time",
    salary: "50-75k",
    datePosted: "2022-07-12",
    description: `QA Experts ensures superior quality standards. Join our team in Rivendell as a Quality Assurance specialist and uphold excellence through meticulous testing. With QA Experts, your precision ensures flawless products.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    name: "Support Solutions",
    position: "Technical Support",
    location: "Gondor",
    type: "Full-time",
    salary: "45-70k",
    datePosted: "2022-06-28",
    description: `Support Solutions provides essential technical assistance. Join our team in Gondor and deliver prompt support to enhance user experience. With Support Solutions, your dedication keeps our services running smoothly.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    name: "Advanced Tech",
    position: "Software Development level 2",
    location: "Elantris",
    type: "Full-time",
    salary: "70-100k",
    datePosted: "2022-05-22",
    description: `Advanced Tech drives innovation in software development. Join our team in Elantris and tackle complex challenges with cutting-edge solutions. With Advanced Tech, your expertise fuels technological advancement.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    name: "Tech Innovations",
    position: "Junior Developer",
    location: "Narnia",
    type: "Full-time",
    salary: "50-80k",
    datePosted: "2022-04-11",
    description: `Tech Innovations pioneers next-generation solutions. Join our team in Narnia as a Junior Developer and contribute to innovative projects that shape the future. With Tech Innovations, your creativity drives digital transformation.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    name: "Elite Developers",
    position: "Senior Developer",
    location: "Brusia",
    type: "Full-time",
    salary: "80-120k",
    datePosted: "2022-03-01",
    description: `Elite Developers leads with expertise and innovation. Join our team in Brusia as a Senior Developer and lead transformative projects. With Elite Developers, your skills redefine possibilities in software development.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    name: "Future Projects",
    position: "Project Manager",
    location: "Zandria",
    type: "Full-time",
    salary: "70-110k",
    datePosted: "2022-02-10",
    description: `Future Projects drives visionary initiatives. Join our team in Zandria as a Project Manager and oversee projects that shape the future. With Future Projects, your leadership propels innovation and success.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/22.jpg",
  },
];

export default companies;
