const companies = [
  {
    name: "Linear Company",
    position: "Software Development level 1",
    location: "Brusia",
    type: "Full-time",
    salary: "60-90k",
    datePosted: "2023-10-28",
    description: `Welcome to accenture.com! In order to provide a more relevant experience for you, we use cookies to enable some website functionality. Cookies help us see which articles most interest you; allow you to easily share articles on social media; permit us to deliver content, jobs and ads tailored to your interests and locations; and provide many other site benefits. For more information, please review our `,
    avatarUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Tech Solutions",
    position: "Junior Developer",
    location: "Zandria",
    type: "Full-time",
    salary: "50-80k",
    datePosted: "2023-09-15",
    description: `We use cookies to provide a better experience on our website.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    name: "Innovatech",
    position: "Senior Developer",
    location: "Netherland",
    type: "Full-time",
    salary: "80-120k",
    datePosted: "2023-08-20",
    description: `We use cookies to personalize content and ads.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Future Systems",
    position: "Project Manager",
    location: "Arboria",
    type: "Full-time",
    salary: "70-110k",
    datePosted: "2023-07-05",
    description: `Cookies help us analyze traffic and improve our services.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    name: "Data Corp",
    position: "Data Analyst",
    location: "Quixonia",
    type: "Full-time",
    salary: "65-95k",
    datePosted: "2023-06-12",
    description: `Our site uses cookies to enhance user experience.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    name: "Net Solutions",
    position: "System Administrator",
    location: "Atlantis",
    type: "Full-time",
    salary: "60-100k",
    datePosted: "2023-05-22",
    description: `We use cookies to support site functionality.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    name: "Creative Minds",
    position: "UX/UI Designer",
    location: "Rivendell",
    type: "Full-time",
    salary: "55-85k",
    datePosted: "2023-04-30",
    description: `Cookies enable us to provide better service.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    name: "Quality Assurance Inc.",
    position: "Quality Assurance",
    location: "Gondor",
    type: "Full-time",
    salary: "50-75k",
    datePosted: "2023-04-10",
    description: `Our website uses cookies for analytics and ads.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    name: "Tech Support Co.",
    position: "Technical Support",
    location: "Elantris",
    type: "Full-time",
    salary: "45-70k",
    datePosted: "2023-03-18",
    description: `We use cookies to understand how you use our site.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    name: "Binary Solutions",
    position: "Software Development level 2",
    location: "Narnia",
    type: "Full-time",
    salary: "70-100k",
    datePosted: "2023-02-25",
    description: `Cookies help us improve user experience.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    name: "Prime Tech",
    position: "Junior Developer",
    location: "Brusia",
    type: "Full-time",
    salary: "50-80k",
    datePosted: "2023-01-30",
    description: `We use cookies to enhance functionality.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    name: "Digital Pioneers",
    position: "Senior Developer",
    location: "Zandria",
    type: "Full-time",
    salary: "80-120k",
    datePosted: "2022-12-15",
    description: `Cookies help us improve our website.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    name: "NextGen Systems",
    position: "Project Manager",
    location: "Netherland",
    type: "Full-time",
    salary: "70-110k",
    datePosted: "2022-11-22",
    description: `Our site uses cookies for better service.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    name: "Insight Analytics",
    position: "Data Analyst",
    location: "Arboria",
    type: "Full-time",
    salary: "65-95k",
    datePosted: "2022-10-10",
    description: `We use cookies to analyze site traffic.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    name: "Network Solutions",
    position: "System Administrator",
    location: "Quixonia",
    type: "Full-time",
    salary: "60-100k",
    datePosted: "2022-09-18",
    description: `Cookies help us deliver better content.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    name: "Design Masters",
    position: "UX/UI Designer",
    location: "Atlantis",
    type: "Full-time",
    salary: "55-85k",
    datePosted: "2022-08-05",
    description: `We use cookies to provide personalized ads.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    name: "QA Experts",
    position: "Quality Assurance",
    location: "Rivendell",
    type: "Full-time",
    salary: "50-75k",
    datePosted: "2022-07-12",
    description: `Cookies help us measure ad performance.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    name: "Support Solutions",
    position: "Technical Support",
    location: "Gondor",
    type: "Full-time",
    salary: "45-70k",
    datePosted: "2022-06-28",
    description: `We use cookies to track site performance.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    name: "Advanced Tech",
    position: "Software Development level 2",
    location: "Elantris",
    type: "Full-time",
    salary: "70-100k",
    datePosted: "2022-05-22",
    description: `Cookies help us understand user behavior.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    name: "Tech Innovations",
    position: "Junior Developer",
    location: "Narnia",
    type: "Full-time",
    salary: "50-80k",
    datePosted: "2022-04-11",
    description: `We use cookies to improve our services.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    name: "Elite Developers",
    position: "Senior Developer",
    location: "Brusia",
    type: "Full-time",
    salary: "80-120k",
    datePosted: "2022-03-01",
    description: `Cookies help us enhance site performance.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    name: "Future Projects",
    position: "Project Manager",
    location: "Zandria",
    type: "Full-time",
    salary: "70-110k",
    datePosted: "2022-02-10",
    description: `Our site uses cookies for a better experience.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    name: "Design Masters",
    position: "UX/UI Designer",
    location: "Atlantis",
    type: "Full-time",
    salary: "55-85k",
    datePosted: "2022-08-05",
    description: `We use cookies to provide personalized ads.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    name: "QA Experts",
    position: "Quality Assurance",
    location: "Rivendell",
    type: "Full-time",
    salary: "50-75k",
    datePosted: "2022-07-12",
    description: `Cookies help us measure ad performance.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    name: "Support Solutions",
    position: "Technical Support",
    location: "Gondor",
    type: "Full-time",
    salary: "45-70k",
    datePosted: "2022-06-28",
    description: `We use cookies to track site performance.`,
    avatarUrl: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    name: "Advanced Tech",
    position: "Software Development level 2",
    location: "Elantris",
    type: "Full-time",
    salary: "70-100k",
    datePosted: "2022-05-22",
    description: `Cookies help us understand user behavior.`,
    avatarUrl: "https://randomuser.me/api/portraits/men/19.jpg",
  },
];

export default companies;
